package com.ecloudiot.framework.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHES.
 */
public class Cache {

    private Long id;
    private String sort1;
    private String sort2;
    private String md5;
    private String content;
    private java.util.Date cache_time;
    private String state;

    public Cache() {
    }

    public Cache(Long id) {
        this.id = id;
    }

    public Cache(Long id, String sort1, String sort2, String md5, String content, java.util.Date cache_time, String state) {
        this.id = id;
        this.sort1 = sort1;
        this.sort2 = sort2;
        this.md5 = md5;
        this.content = content;
        this.cache_time = cache_time;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSort1() {
        return sort1;
    }

    public void setSort1(String sort1) {
        this.sort1 = sort1;
    }

    public String getSort2() {
        return sort2;
    }

    public void setSort2(String sort2) {
        this.sort2 = sort2;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getCache_time() {
        return cache_time;
    }

    public void setCache_time(java.util.Date cache_time) {
        this.cache_time = cache_time;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

}
